# Generated by Django 3.2.14 on 2022-07-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
